name: Deploy to Server

on:
  push:
    branches: [master]
  repository_dispatch:
    types: [iris-kakao-bot-updated]

jobs:
  deploy:
    runs-on: [self-hosted, wikibot]
    steps:
      - name: Deploy
        run: |
          cd ~/wikibot-kakao
          ./deploy.sh --force
